version: "3"

services:
  backend:
    build: 
      context: ./Backend/
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3333:3333"
    networks: 
      - "koob_net"
    volumes:
      - ./Backend/:/usr/app/
    depends_on: 
      - mysql
    environment: 
      - MYSQL_HOST=backend_koob
      - MYSQL_USER=edu
      - MYSQL_PASS=eduardo123
      - MYSQL_DB=koobdb
    container_name: backend_koob
  frontend:
    build: 
      context: ./Frontend/
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3002:3002"
    networks: 
      - "koob_net"
    volumes:
      - ./Frontend/:/usr/app/
      - '/usr/app/node_modules'
    depends_on: 
      - backend
    environment: 
      - MYSQL_HOST=frontend_koob
      - MYSQL_USER=edu
      - MYSQL_PASS=eduardo123
      - MYSQL_DB=koobdb
    container_name: frontend_koob

  mysql:
    image: mysql
    networks: 
      - "koob_net"
    environment: 
      - MYSQL_ROOT_PASSWORD=eduardo123
      - MYSQL_USER=edu
      - MYSQL_PASS=eduardo123
      - MYSQL_DB=koobdb
    container_name: mysql_koob
    ports:
      - "3306:3306"

networks:
  koob_net:
    external: true